# Generated by Django 5.0.7 on 2024-07-26 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=30)),
                ('active', models.BooleanField()),
                ('datecreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
